package com.vivo.services.superresolution;

import android.os.SystemProperties;
import com.vivo.framework.superresolution.SuperResolutionConfig;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/* loaded from: classes.dex */
public class Constant {
    public static final String ACTIVITY_DOUYIN_LAUNCHER = "com.ss.android.ugc.aweme.main.MainActivity";
    public static final String ACTIVITY_DOUYIN_PHOTE_EDIT = "com.ss.android.ugc.aweme.photo.edit.PhotoEditActivity";
    public static final String ACTIVITY_DOUYIN_SPLASH = "com.ss.android.ugc.aweme.splash.SplashActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_BROWSER = "com.ss.android.ugc.aweme.im.sdk.msgdetail.MediaBrowserActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_CUT = "com.ss.android.ugc.aweme.shortvideo.cut.VECutVideoActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_EDIT = "com.ss.android.ugc.aweme.story.shootvideo.VideoStoryEditPublishActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_LIVE_DETAIL = "com.ss.android.ugc.aweme.detail.ui.LiveDetailActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_LIVE_PLAY = "com.ss.android.ugc.aweme.live.LivePlayActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_MAIN = "com.ss.android.ugc.aweme.main.MainActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_OTHER = "com.ss.android.ugc.aweme.detail.ui.DetailActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_PREVIEW = "com.ss.android.ugc.aweme.shortvideo.ui.VEVideoPublishPreviewActivity";
    public static final String ACTIVITY_DOUYIN_VIDEO_RECORD = "com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity";
    public static final String ACTIVITY_DOUYU_HOMEPAGE = "com.douyu.module.home.pages.main.MainActivity";
    public static final String ACTIVITY_DOUYU_LAUNCHER = "com.douyu.module.home.pages.main.MainActivity";
    public static final String ACTIVITY_DOUYU_LIVEROOM = "tv.douyu.view.activity.PlayerActivity";
    public static final String ACTIVITY_DOUYU_SPLASH = "tv.douyu.view.activity.launcher.DYSplashLauncherActivity";
    public static final String ACTIVITY_DOUYU_VOD = "com.douyu.module.vod.view.activity.DYVodActivity";
    public static final String ACTIVITY_GALLERY = "com.android.gallery3d.app.Gallery";
    public static final String ACTIVITY_GALLERY_NEW = "com.android.gallery3d.vivo.NewPageActivity";
    public static final String ACTIVITY_GALLERY_TAB = "com.android.gallery3d.vivo.GalleryTabActivity";
    public static final String ACTIVITY_HUYA_HOMEPAGE = "com.duowan.kiwi.homepage.Homepage";
    public static final String ACTIVITY_HUYA_LIVEROOM = "com.duowan.kiwi.liveroom.ChannelPage";
    public static final String ACTIVITY_HUYA_SPLASH = "com.duowan.kiwi.simpleactivity.SplashActivity";
    public static final String ACTIVITY_HUYA_VIDEO = "com.duowan.kiwi.videopage.ui.DetailVideoPageActivity";
    public static final String ACTIVITY_LAUNCHER = "com.bbk.launcher2.Launcher";
    public static final String ACTIVITY_LAUNCHER_SMART = "com.vivo.smartmultiwindow.minilauncher2.Launcher";
    public static final String ACTIVITY_TOUTIAO = "com.ss.android.detail.feature.detail2.view.NewVideoDetailActivity";
    public static final String ACTIVITY_TOUTIAO_DETAIL = "com.ss.android.detail.feature.detail2.view.NewDetailActivity";
    public static final String ACTIVITY_TOUTIAO_HOMEPAGE = "com.ss.android.article.news.activity.MainActivity";
    public static final String ACTIVITY_TOUTIAO_LAUNCHER = "com.ss.android.article.news.activity.LaunchActivity";
    public static final String ACTIVITY_TOUTIAO_MAIN = "com.ss.android.article.news.activity.MainActivity";
    public static final String ACTIVITY_TOUTIAO_SPLASH = "com.ss.android.article.news.activity.SplashBadgeActivity";
    public static final String ACTIVITY_WEIBO_FEED_DETAIL = "com.sina.weibo.feed.DetailWeiboActivity";
    public static final String ACTIVITY_WEIBO_HPMEPAGE = "com.sina.weibo.MainTabActivity";
    public static final String ACTIVITY_WEIBO_MAIN = "com.sina.weibo.VisitorMainTabActivity";
    public static final String ACTIVITY_WEIBO_MAIN_TAB = "com.sina.weibo.MainTabActivity";
    public static final String ACTIVITY_WEIBO_PHOTOALBUM_IMAGEVIEWER = "com.sina.weibo.photoalbum.imageviewer.ImageViewer";
    public static final String ACTIVITY_WEIBO_PROFILE_INFO = "com.sina.weibo.page.ProfileInfoActivity";
    public static final String ACTIVITY_WEIBO_SPLASH = "com.sina.weibo.SplashActivity";
    public static final String ACTIVITY_WEIBO_STORY_GALLERY = "com.sina.weibo.story.gallery.activity.VVSActivity";
    public static final String ACTIVITY_WEIBO_TV_PLAYER = "com.sina.weibotv.xiaoka.play.activity.PlayerContainerActivity";
    public static final String ACTIVITY_WEIBO_VIDEO_CONTAINER = "com.sina.weibo.video.tabcontainer.VideoTabContainerActivity";
    public static final String ACTIVITY_WEIBO_VIDEO_DETAIL = "com.sina.weibo.video.detail.VideoDetailActivity";
    public static final String ACTIVITY_WEIBO_VISITOR_MAIN_TAB = "com.sina.weibo.VisitorMainTabActivity";
    public static final String ACTIVITY_WEIXIN_FRIENDS_ZONE = "com.tencent.mm.plugin.sns.ui.SnsTimeLineUI";
    public static final String ACTIVITY_WEIXIN_HOMEPAGE = "com.tencent.mm.ui.LauncherUI";
    public static final String ACTIVITY_WEIXIN_IMAGE = "com.tencent.mm.ui.chatting.gallery.ImageGalleryUI";
    public static final String ACTIVITY_WEIXIN_NO_SR = "activity_wechat_no_sr";
    public static final String ACTIVITY_WEIXIN_RECORD_FINDER = "com.tencent.mm.plugin.finder.feed.ui.FinderTimelineUI";
    public static final String ACTIVITY_WEIXIN_SHARE_GALLERY = "com.tencent.mm.plugin.sns.ui.SnsGalleryUI";
    public static final String ACTIVITY_WEIXIN_SHARE_IMAGE = "com.tencent.mm.plugin.sns.ui.SnsBrowseUI";
    public static final String ACTIVITY_WEIXIN_SHARE_VIDEO = "com.tencent.mm.plugin.sns.ui.SnsOnlineVideoActivity";
    public static final String ACTIVITY_WEIXIN_SPLASH = "com.tencent.mm.app.WeChatSplashActivity";
    public static final String ACTIVITY_WEIXIN_USER_FRIENDS_ZONE = "com.tencent.mm.plugin.sns.ui.SnsUserUI";
    public static final String ACTIVITY_WEIXIN_VIDEO = "com.tencent.mm.plugin.voip.ui.VideoActivity";
    public static final String ACTIVITY_WEIXIN_VIDEO_MULTI = "com.tencent.mm.plugin.multitalk.ui.MultiTalkMainUI";
    public static final String APP_DOUYIN = "com.ss.android.ugc.aweme";
    public static final String APP_DOUYU = "air.tv.douyu.android";
    public static final String APP_GALLERY = "com.vivo.gallery";
    public static final String APP_HUYA = "com.duowan.kiwi";
    public static final int APP_SHARE = 3;
    public static final int APP_SWITCH_CHANGE = 1;
    public static final String APP_TOUTIAO = "com.ss.android.article.news";
    public static final String APP_WEIBO = "com.sina.weibo";
    public static final String APP_WEIXIN = "com.tencent.mm";
    public static int CHECK_TEMPERATURE_TIME = 0;
    public static final int CMD_ID_CLEAR_ALL_HANDLES = 7;
    public static final int CMD_ID_CREATE_CONNECTION = 6;
    public static final int CMD_ID_GET_OUT_SIZE = 2;
    public static final int CMD_ID_INIT_GRALLERY = 10;
    public static final int CMD_ID_RELEASE = 4;
    public static final int CMD_ID_RESIZEBILINEAR = 5;
    public static final int CMD_ID_RUN = 3;
    public static final int CMD_ID_SET_IS_SCREEN_ON = 8;
    public static final int CUR_MODEL = 100;
    public static final String CUSTOM_TEMPURE = "custom_tempure";
    public static final String DATA_REPORT_HIGH_TEMPERATURE = "4";
    public static final String DATA_REPORT_LOW_POWER = "2";
    public static final long DAY_TIME = 86400000;
    public static final String[] DEFAULT_SUPPORT_APP;
    public static final int MAIN_SWITCH_CHANGE = 0;
    public static final String MEMC_SETTING_VALUE_MAIN = "memc_main";
    public static final int MILLILS_OF_WEEK = 604800000;
    public static final int MSG_APP_INSTALL = 12;
    public static final int MSG_APP_REMOVE = 13;
    public static final int MSG_GET_UNIFIED_CONFIG = 11;
    public static final int MSG_INIT_STOP_SCENE = 1;
    public static final int MSG_REPORT_SWITCH_OFF = 3;
    public static final int MSG_REPORT_TIMER = 14;
    public static final int MSG_RESET_TIMER = 20;
    public static final int MSG_WINDOW_CHANGE = 4;
    public static final int MULTI_SCREEN_CHANGE = 2;
    public static String[] NEW_DEVICE_SUPPORT_APP = null;
    public static final String OPEN_HIGH_TEMPURE_FORBID = "open_high_tempure_forbid";
    public static final String POWER_SAVE_TYPE = "power_save_type";
    public static final int REPORT_SPACE = 604;
    public static final int SETTING_LOW_POWER = 2;
    public static final String SETTING_STOP_TYPE = "super_resolution_stop_state";
    public static final String SETTING_VALUE_APPS = "super_resolution_apps";
    public static final String SETTING_VALUE_MAIN = "super_resolution_main";
    public static final String SETTING_VALUE_SEED = "super_resolution_seed";
    public static String[] SM8350_SUPPORT_APP = null;
    public static final String SR_CONFIG_BROADCAST = "com.vivo.daemonService.unifiedconfig.update_finish_broadcast_super_resolution";
    public static final String SR_CONFIG_FILE_PATH = "/data/bbkcore/super_resolution_sr_config_1.0.xml";
    public static final String SR_CONFIG_MAX_TEMPERATURE = "sr_max_temperature";
    public static final String SR_CONFIG_NAME = "sr_config";
    public static final String SR_CONFIG_SUPPORT_APPS = "sr_support_apps";
    public static final int STATE_APP_SHARE_RUNNING = 10;
    public static final int STATE_SR_CLOSE = 0;
    public static final int STATE_SR_OPEN = 1;
    public static final int STATE_SUPER_RESOLUTION_UNISTALL = -1;
    public static final int STATUS_MEMC_CLOSE = 0;
    public static final int STATUS_MEMC_OPEN = 1;
    public static final int STOP_SCENE_TYPE_DEFAULT = 0;
    public static final int STOP_SCENE_TYPE_FLOAT_BALL = 5;
    public static final int STOP_SCENE_TYPE_HIGH_TEMPERATURE = 1;
    public static final int STOP_SCENE_TYPE_HIGH_TEMP_LOW_POWER = 4;
    public static final int STOP_SCENE_TYPE_LOW_POWER = 3;
    public static final int STOP_SCENE_TYPE_SETTING = 10;
    public static final int STOP_SCENE_TYPE_SUPER_POWER = 2;
    public static final String SUPER_RESOLUTION_APPS_ALPHA_ANIMATOR = "super_resolution_apps_alpha_animator";
    public static final String SUPER_RESOLUTION_FIRST_APP = "super_resolution_first_app";
    public static String[] SUPPORT_APP = null;
    public static String[] SUPPORT_APP_SETTINGS = null;
    public static final String[] SUPPORT_DEVICES;
    public static final String SYSTEM_DIALOG_REASON_HOME_KEY = "homekey";
    public static final String SYSTEM_SUPER_RESOLUTION_SWITCH = "persist.sys.superresolution";
    public static int TEMPERATURE_MAX = 0;
    public static final String[] THIRD_PARTY_APP;
    public static final int VALUE_SWITCH_OFF = 0;
    public static final int VALUE_SWITCH_ON = 1;
    public static final String PLATFORM = SystemProperties.get("ro.vivo.product.platform", "unknown");
    public static final String MODEL = SystemProperties.get("ro.vivo.product.model", "unknown");
    public static final boolean IS_OVERSEAS = "yes".equals(SystemProperties.get("ro.vivo.product.overseas", "no"));
    public static final ArrayList<String> sSuportActivityList = new ArrayList<>();
    public static final ArrayList<String> mSuportLauncherActivityList = new ArrayList<>();
    public static final ArrayList<String> mSplashActivity = new ArrayList<>();
    public static final Map<String, Integer> sAppSwitch = new HashMap();
    public static final List<String> sInstalledPackages = new ArrayList();
    public static int SWITCH_CLOSE_ALL = 0;
    public static int SWITCH_OPEN_ALL = -1;
    public static int SWITCH_WECHAT_VIDEO_CALL = Integer.MIN_VALUE;
    public static int SWITCH_WECHAT_SHARE_VIDEO = 1073741824;
    public static int SWITCH_APP_DOUYU = 32;
    public static int SWITCH_APP_HUYA = 16;
    public static int SWITCH_APP_TOUTIAO = 8;
    public static int SWITCH_APP_WEIBO = 4;
    public static int SWITCH_APP_DOUYIN = 2;
    public static int SWITCH_APP_WECHAT = 1;

    static {
        mSuportLauncherActivityList.add("com.sina.weibo.VisitorMainTabActivity");
        mSuportLauncherActivityList.add("com.sina.weibo.MainTabActivity");
        mSuportLauncherActivityList.add("com.douyu.module.home.pages.main.MainActivity");
        mSuportLauncherActivityList.add(ACTIVITY_HUYA_SPLASH);
        mSuportLauncherActivityList.add("com.ss.android.article.news.activity.MainActivity");
        mSuportLauncherActivityList.add("com.ss.android.ugc.aweme.main.MainActivity");
        mSuportLauncherActivityList.add(ACTIVITY_TOUTIAO_LAUNCHER);
        mSplashActivity.add(ACTIVITY_WEIBO_SPLASH);
        mSplashActivity.add(ACTIVITY_DOUYU_SPLASH);
        mSplashActivity.add(ACTIVITY_TOUTIAO_SPLASH);
        mSplashActivity.add(ACTIVITY_DOUYIN_SPLASH);
        sSuportActivityList.add("com.ss.android.ugc.aweme.main.MainActivity");
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_OTHER);
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_PREVIEW);
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_RECORD);
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_LIVE_DETAIL);
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_CUT);
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_BROWSER);
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_EDIT);
        sSuportActivityList.add(ACTIVITY_DOUYIN_VIDEO_LIVE_PLAY);
        sSuportActivityList.add(ACTIVITY_DOUYIN_PHOTE_EDIT);
        sSuportActivityList.add("com.sina.weibo.MainTabActivity");
        sSuportActivityList.add("com.sina.weibo.VisitorMainTabActivity");
        sSuportActivityList.add(ACTIVITY_WEIBO_VIDEO_CONTAINER);
        sSuportActivityList.add(ACTIVITY_WEIBO_VIDEO_DETAIL);
        sSuportActivityList.add(ACTIVITY_WEIBO_FEED_DETAIL);
        sSuportActivityList.add(ACTIVITY_WEIBO_TV_PLAYER);
        sSuportActivityList.add(ACTIVITY_WEIBO_STORY_GALLERY);
        sSuportActivityList.add(ACTIVITY_WEIBO_PROFILE_INFO);
        sSuportActivityList.add(ACTIVITY_WEIBO_PHOTOALBUM_IMAGEVIEWER);
        sSuportActivityList.add(ACTIVITY_WEIXIN_VIDEO);
        sSuportActivityList.add(ACTIVITY_WEIXIN_IMAGE);
        sSuportActivityList.add(ACTIVITY_WEIXIN_SHARE_IMAGE);
        sSuportActivityList.add(ACTIVITY_WEIXIN_SHARE_VIDEO);
        sSuportActivityList.add(ACTIVITY_WEIXIN_VIDEO_MULTI);
        sSuportActivityList.add(ACTIVITY_WEIXIN_RECORD_FINDER);
        sSuportActivityList.add(ACTIVITY_HUYA_LIVEROOM);
        sSuportActivityList.add(ACTIVITY_HUYA_VIDEO);
        sSuportActivityList.add("com.douyu.module.home.pages.main.MainActivity");
        sSuportActivityList.add(ACTIVITY_DOUYU_LIVEROOM);
        sSuportActivityList.add(ACTIVITY_DOUYU_VOD);
        sSuportActivityList.add(ACTIVITY_TOUTIAO);
        sSuportActivityList.add(ACTIVITY_TOUTIAO_DETAIL);
        sSuportActivityList.add("com.ss.android.article.news.activity.MainActivity");
        sSuportActivityList.add(ACTIVITY_GALLERY_NEW);
        if (PLATFORM.equals("SM8350")) {
            sAppSwitch.put(APP_GALLERY, 1);
            sAppSwitch.put(APP_DOUYU, 1);
        } else if (SuperResolutionConfig.IS_SUPPORT_SUPER_RESOLUTION_NEW_DEVICE) {
            sAppSwitch.put(APP_GALLERY, 1);
        } else {
            sAppSwitch.put(APP_WEIXIN, 1);
            sAppSwitch.put(APP_DOUYIN, 1);
            sAppSwitch.put(APP_GALLERY, 1);
            sAppSwitch.put(APP_DOUYU, 1);
            sAppSwitch.put(APP_HUYA, 1);
            sAppSwitch.put(APP_WEIBO, 1);
            sAppSwitch.put(APP_TOUTIAO, 1);
        }
        TEMPERATURE_MAX = 47;
        CHECK_TEMPERATURE_TIME = 30000;
        SUPPORT_DEVICES = new String[]{"PD1981", "PD2001", "PD2011", "PD2005", "PD2012", "PD2020", "PD2024", "PD2025"};
        DEFAULT_SUPPORT_APP = new String[]{APP_GALLERY, APP_WEIXIN, APP_DOUYIN, APP_WEIBO, APP_TOUTIAO, APP_HUYA, APP_DOUYU};
        SUPPORT_APP = new String[]{APP_GALLERY, APP_WEIXIN, APP_DOUYIN, APP_WEIBO, APP_TOUTIAO, APP_HUYA, APP_DOUYU};
        NEW_DEVICE_SUPPORT_APP = new String[]{APP_GALLERY};
        THIRD_PARTY_APP = new String[]{APP_WEIXIN, APP_DOUYIN, APP_WEIBO, APP_TOUTIAO, APP_HUYA, APP_DOUYU};
        SUPPORT_APP_SETTINGS = new String[]{APP_GALLERY, APP_DOUYIN, APP_WEIBO, APP_TOUTIAO, APP_HUYA, APP_DOUYU};
        SM8350_SUPPORT_APP = new String[]{APP_GALLERY, APP_DOUYU};
    }
}