package com.android.server.wm;

import android.os.Build;
import android.os.FtBuild;
import android.os.SystemProperties;
import android.util.FtFeature;

/* loaded from: classes.dex */
public abstract class VivoMultiWindowFeature {
    static final boolean IS_CAN_RELOAD_SPLIT_PROPS = SystemProperties.getBoolean("persist.vivo.multiwindow_can_reload_split_Properties", false);
    public static boolean IS_TEMP_HIDE_STATUS_FOR_SPECIAL = false;
    public static boolean IS_VIVO_AM_RELAUNCH_PROPERTY = false;
    public static boolean IS_VIVO_AM_RESIZABLE_PROPERTY = false;
    public static boolean IS_VIVO_APPLIST_RETURN_MINIMIZE = false;
    public static boolean IS_VIVO_AVOID_MOVE_FOCUS_TO_PRIMARY = false;
    public static boolean IS_VIVO_CHANGE_LAUNCH_STACK = false;
    public static boolean IS_VIVO_DEFER_ROTATE = false;
    public static boolean IS_VIVO_DOCK_FINISH_HOME_MINIMIZED = false;
    public static boolean IS_VIVO_DOUBLE_RESUME_PROPERTY = false;
    public static boolean IS_VIVO_ENABLE_DELAY_HIDE_SPLITNABAR_INSPLIT = false;
    public static boolean IS_VIVO_ENTER_SPLIT_OPTIMIZE = false;
    public static boolean IS_VIVO_FORCE_DEBUG_TASK_BOUNDS = false;
    public static boolean IS_VIVO_HIDE_SPLIT_APPLIST = false;
    public static boolean IS_VIVO_INTO_SPLIT_OPTIMIZE = false;
    public static boolean IS_VIVO_LAYOUT_INCLUDE_NAVBAR = false;
    public static boolean IS_VIVO_MODIFY_HOME_LAYER = false;
    public static boolean IS_VIVO_MODIFY_TENCENT_TOP = false;
    public static boolean IS_VIVO_NORESIZE_INROTATE = false;
    public static boolean IS_VIVO_REPARENT_WHEN_IMMEDIATE_DESTROY = false;
    public static boolean IS_VIVO_ROTATE_FREE = false;
    public static boolean IS_VIVO_ROTATE_SUGGESTION = false;
    public static boolean IS_VIVO_SHOW_DIVIDER_BG = false;
    public static boolean IS_VIVO_SHOW_DIVIDER_BG_FORCE = false;
    public static boolean IS_VIVO_SKIP_ADJUST_IME = false;
    public static boolean IS_VIVO_SPLIT_BACK_PROCESS = false;
    public static boolean IS_VIVO_SPLIT_DIVIDER = false;
    public static boolean IS_VIVO_SPLIT_DIVIDER_LAYER = false;
    public static boolean IS_VIVO_SPLIT_DOUBLE_DISPLAYS = false;
    public static boolean IS_VIVO_SPLIT_DRAGDROP = false;
    public static boolean IS_VIVO_SPLIT_FORCE_IGNORE_AFTER_BACK = false;
    public static boolean IS_VIVO_SPLIT_FORCE_LAND_CUTOUT = false;
    public static boolean IS_VIVO_SPLIT_HIDE_STATUSBAR = false;
    public static boolean IS_VIVO_SPLIT_NAV_COLOR = false;
    public static boolean IS_VIVO_SPLIT_NOT_DEFAULT_LAUNCHER = false;
    public static boolean IS_VIVO_SPLIT_PROTECT_APP = false;
    public static boolean IS_VIVO_SPLIT_SAFE_LAND_CUTOUT = false;
    public static boolean IS_VIVO_SPLIT_SOFTLOCK_SPECIAL = false;
    public static boolean IS_VIVO_SPLIT_SPLITFULL_ANIM = false;
    public static boolean IS_VIVO_SPLIT_SWITCH_ANIM = false;
    public static boolean IS_VIVO_SPLIT_THIRD_LAUNCHER = false;
    public static boolean IS_VIVO_SUPPORT_LANDSCAPE_LAUNCHER = false;
    public static boolean IS_VIVO_SUPPORT_MULTIWINDOW_DEBUG_PROPERTY = false;
    public static boolean IS_VIVO_SUPPORT_MULTIWINDOW_PROPERTY = false;
    public static boolean IS_VIVO_SUPPORT_NIGHTMODE_PROPERTY = false;
    public static boolean IS_VIVO_SYSTEMBAR_IMMERSE_FORCE = false;
    public static boolean IS_VIVO_USE_MIDDLETARGET_AFTER_ROTATION = false;
    public static boolean IS_VIVO_USE_SAME_TRANSATION = false;
    private static final String myTag = "SplitFeature";

    static {
        IS_VIVO_SUPPORT_MULTIWINDOW_DEBUG_PROPERTY = SystemProperties.getBoolean("persist.vivo.multiwindow_debug", Build.IS_USERDEBUG || Build.IS_ENG);
        IS_VIVO_SUPPORT_MULTIWINDOW_PROPERTY = FtFeature.isFeatureSupport("vivo.software.multiwindow");
        IS_VIVO_SUPPORT_NIGHTMODE_PROPERTY = FtFeature.isFeatureSupport("vivo.software.nightmode");
        IS_VIVO_AM_RESIZABLE_PROPERTY = SystemProperties.getBoolean("persist.vivo.multiwindow_am_resizable", true);
        IS_VIVO_AM_RELAUNCH_PROPERTY = SystemProperties.getBoolean("persist.vivo.multiwindow_am_relaunch", true);
        IS_VIVO_DOUBLE_RESUME_PROPERTY = SystemProperties.getBoolean("persist.vivo.double_resume", true);
        IS_VIVO_SHOW_DIVIDER_BG = SystemProperties.getBoolean("persist.vivo.divider_bg", true);
        IS_VIVO_SHOW_DIVIDER_BG_FORCE = SystemProperties.getBoolean("persist.vivo.divider_bg_force", false);
        IS_VIVO_DOCK_FINISH_HOME_MINIMIZED = SystemProperties.getBoolean("persist.vivo.dock_finish_minimized", true);
        IS_VIVO_ROTATE_FREE = SystemProperties.getBoolean("persist.vivo.multiwindow_rotatevalid", false);
        IS_VIVO_ROTATE_SUGGESTION = SystemProperties.getBoolean("persist.vivo.multiwindow_rotate_suggestion", true);
        IS_VIVO_NORESIZE_INROTATE = SystemProperties.getBoolean("persist.vivo.multiwindow_noresize_inrotate", true);
        IS_VIVO_LAYOUT_INCLUDE_NAVBAR = SystemProperties.getBoolean("persist.vivo.multiwindow_layout_include_navbar", true);
        IS_VIVO_DEFER_ROTATE = SystemProperties.getBoolean("persist.vivo.multiwindow_defer_minimize_rotate", false);
        IS_VIVO_SKIP_ADJUST_IME = SystemProperties.getBoolean("persist.vivo.multiwindow_skip_adjusted_ime", true);
        IS_VIVO_SPLIT_FORCE_LAND_CUTOUT = SystemProperties.getBoolean("persist.vivo.multiwindow_split_force_cutout", true);
        IS_VIVO_SPLIT_FORCE_IGNORE_AFTER_BACK = SystemProperties.getBoolean("persist.vivo.multiwindow_split_force_ignore_after_back", true);
        IS_VIVO_USE_MIDDLETARGET_AFTER_ROTATION = SystemProperties.getBoolean("persist.vivo.multiwindow_use_middletarget_after_rotation", true);
        IS_VIVO_SUPPORT_LANDSCAPE_LAUNCHER = SystemProperties.getBoolean("persist.vivo.support_landscape_launcher", FtBuild.isOverSeas() || FtBuild.getRomVersion() < 12.0f);
        IS_VIVO_ENTER_SPLIT_OPTIMIZE = SystemProperties.getBoolean("persist.vivo.multiwindow_enter_split_optimize", true);
        IS_VIVO_ENABLE_DELAY_HIDE_SPLITNABAR_INSPLIT = SystemProperties.getBoolean("persist.vivo.enable_delay_hide_splitnabar_insplit", true);
        IS_VIVO_FORCE_DEBUG_TASK_BOUNDS = SystemProperties.getBoolean("persist.vivo.force.debug.task.bounds", false);
        IS_VIVO_AVOID_MOVE_FOCUS_TO_PRIMARY = SystemProperties.getBoolean("persist.vivo.avoid_move_focus", true);
        IS_VIVO_SYSTEMBAR_IMMERSE_FORCE = SystemProperties.getBoolean("persisit.vivo.multiwindow_systembar_immerse_force", true);
        IS_VIVO_APPLIST_RETURN_MINIMIZE = SystemProperties.getBoolean("persisit.vivo.multiwindow_applist_return_minimize", true);
        IS_VIVO_CHANGE_LAUNCH_STACK = SystemProperties.getBoolean("persist.vivo.multiwindow_change_launch_stack", true);
        IS_VIVO_SPLIT_NAV_COLOR = SystemProperties.getBoolean("persist.vivo.multiwindow_split_nav_color_on", true);
        IS_VIVO_SPLIT_NOT_DEFAULT_LAUNCHER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_notdefault_launcher", true);
        IS_VIVO_SPLIT_SAFE_LAND_CUTOUT = SystemProperties.getBoolean("persist.vivo.multiwindow_split_safe_cutout", true);
        IS_VIVO_SPLIT_SWITCH_ANIM = SystemProperties.getBoolean("persist.vivo.multiwindow_split_switch_anim", true);
        IS_VIVO_SPLIT_SPLITFULL_ANIM = SystemProperties.getBoolean("persist.vivo.multiwindow_splittofull_anim", true);
        IS_VIVO_SPLIT_BACK_PROCESS = SystemProperties.getBoolean("persist.vivo.multiwindow_backlogic_v5.1", true);
        IS_VIVO_SPLIT_SOFTLOCK_SPECIAL = SystemProperties.getBoolean("persist.vivo.multiwindow_softlock_special", true);
        IS_VIVO_SPLIT_HIDE_STATUSBAR = SystemProperties.getBoolean("persist.vivo.multiwindow_hide_statusbar", true);
        IS_VIVO_REPARENT_WHEN_IMMEDIATE_DESTROY = SystemProperties.getBoolean("persist.vivo.multiwindow_reparent_immediate_destroy", true);
        IS_VIVO_SPLIT_DRAGDROP = SystemProperties.getBoolean("persist.vivo.multiwindow_dragdrop", true);
        IS_VIVO_HIDE_SPLIT_APPLIST = SystemProperties.getBoolean("persist.vivo.multiwindow_hide_applist", true);
        IS_VIVO_SPLIT_PROTECT_APP = SystemProperties.getBoolean("persist.vivo.multiwindow_split_protect_app", true);
        IS_VIVO_SPLIT_DIVIDER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_divider_special", false);
        IS_VIVO_SPLIT_DIVIDER_LAYER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_divider_layer", true);
        IS_TEMP_HIDE_STATUS_FOR_SPECIAL = SystemProperties.getBoolean("persist.vivo.multiwindow_temp_hidestatusbar_special", true);
        IS_VIVO_SPLIT_THIRD_LAUNCHER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_third_launcher", true);
        IS_VIVO_INTO_SPLIT_OPTIMIZE = SystemProperties.getBoolean("persist.vivo.multiwindow_into_split_optimize", true);
        IS_VIVO_SPLIT_DOUBLE_DISPLAYS = SystemProperties.getBoolean("persist.vivo.multiwindow_split_double_displays", true);
        IS_VIVO_MODIFY_TENCENT_TOP = SystemProperties.getBoolean("persist.vivo.multiwindow_modify_tencent_top", true);
        IS_VIVO_MODIFY_HOME_LAYER = SystemProperties.getBoolean("persist.vivo.multiwindow_modify_home_layer", false);
        IS_VIVO_USE_SAME_TRANSATION = SystemProperties.getBoolean("persist.vivo.multiwindow_use_same_transtion", true);
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public static void reloadSplitSystemProperties() {
        if (!IS_CAN_RELOAD_SPLIT_PROPS) {
            return;
        }
        IS_VIVO_SUPPORT_MULTIWINDOW_DEBUG_PROPERTY = SystemProperties.getBoolean("persist.vivo.multiwindow_debug", Build.IS_USERDEBUG || Build.IS_ENG);
        IS_VIVO_SUPPORT_MULTIWINDOW_PROPERTY = FtFeature.isFeatureSupport("vivo.software.multiwindow");
        IS_VIVO_SUPPORT_NIGHTMODE_PROPERTY = FtFeature.isFeatureSupport("vivo.software.nightmode");
        IS_VIVO_AM_RESIZABLE_PROPERTY = SystemProperties.getBoolean("persist.vivo.multiwindow_am_resizable", true);
        IS_VIVO_AM_RELAUNCH_PROPERTY = SystemProperties.getBoolean("persist.vivo.multiwindow_am_relaunch", true);
        IS_VIVO_DOUBLE_RESUME_PROPERTY = SystemProperties.getBoolean("persist.vivo.double_resume", true);
        IS_VIVO_SHOW_DIVIDER_BG = SystemProperties.getBoolean("persist.vivo.divider_bg", true);
        IS_VIVO_SHOW_DIVIDER_BG_FORCE = SystemProperties.getBoolean("persist.vivo.divider_bg_force", false);
        IS_VIVO_DOCK_FINISH_HOME_MINIMIZED = SystemProperties.getBoolean("persist.vivo.dock_finish_minimized", true);
        IS_VIVO_ROTATE_FREE = SystemProperties.getBoolean("persist.vivo.multiwindow_rotatevalid", false);
        IS_VIVO_ROTATE_SUGGESTION = SystemProperties.getBoolean("persist.vivo.multiwindow_rotate_suggestion", true);
        IS_VIVO_LAYOUT_INCLUDE_NAVBAR = SystemProperties.getBoolean("persist.vivo.multiwindow_layout_include_navbar", true);
        IS_VIVO_DEFER_ROTATE = SystemProperties.getBoolean("persist.vivo.multiwindow_defer_minimize_rotate", false);
        IS_VIVO_SUPPORT_LANDSCAPE_LAUNCHER = SystemProperties.getBoolean("persist.vivo.support_landscape_launcher", FtBuild.isOverSeas() || FtBuild.getRomVersion() < 12.0f);
        IS_VIVO_SKIP_ADJUST_IME = SystemProperties.getBoolean("persist.vivo.multiwindow_skip_adjusted_ime", true);
        IS_VIVO_SPLIT_FORCE_LAND_CUTOUT = SystemProperties.getBoolean("persist.vivo.multiwindow_split_force_cutout", true);
        IS_VIVO_SPLIT_FORCE_IGNORE_AFTER_BACK = SystemProperties.getBoolean("persist.vivo.multiwindow_split_force_ignore_after_back", true);
        IS_VIVO_USE_MIDDLETARGET_AFTER_ROTATION = SystemProperties.getBoolean("persist.vivo.multiwindow_use_middletarget_after_rotation", true);
        IS_VIVO_AVOID_MOVE_FOCUS_TO_PRIMARY = SystemProperties.getBoolean("persist.vivo.avoid_move_focus", true);
        IS_VIVO_SYSTEMBAR_IMMERSE_FORCE = SystemProperties.getBoolean("persisit.vivo.multiwindow_systembar_immerse_force", true);
        IS_VIVO_APPLIST_RETURN_MINIMIZE = SystemProperties.getBoolean("persisit.vivo.multiwindow_applist_return_minimize", true);
        IS_VIVO_CHANGE_LAUNCH_STACK = SystemProperties.getBoolean("persist.vivo.multiwindow_change_launch_stack", true);
        IS_VIVO_SPLIT_NAV_COLOR = SystemProperties.getBoolean("persist.vivo.multiwindow_split_nav_color_on", true);
        IS_VIVO_SPLIT_NOT_DEFAULT_LAUNCHER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_notdefault_launcher", true);
        IS_VIVO_SPLIT_SAFE_LAND_CUTOUT = SystemProperties.getBoolean("persist.vivo.multiwindow_split_safe_cutout", true);
        IS_VIVO_SPLIT_SWITCH_ANIM = SystemProperties.getBoolean("persist.vivo.multiwindow_split_switch_anim", true);
        IS_VIVO_SPLIT_SPLITFULL_ANIM = SystemProperties.getBoolean("persist.vivo.multiwindow_splittofull_anim", true);
        IS_VIVO_SPLIT_BACK_PROCESS = SystemProperties.getBoolean("persist.vivo.multiwindow_backlogic_v5.1", true);
        IS_VIVO_SPLIT_SOFTLOCK_SPECIAL = SystemProperties.getBoolean("persist.vivo.multiwindow_softlock_special", true);
        IS_VIVO_SPLIT_HIDE_STATUSBAR = SystemProperties.getBoolean("persist.vivo.multiwindow_hide_statusbar", true);
        IS_VIVO_REPARENT_WHEN_IMMEDIATE_DESTROY = SystemProperties.getBoolean("persist.vivo.multiwindow_reparent_immediate_destroy", true);
        IS_VIVO_SPLIT_DRAGDROP = SystemProperties.getBoolean("persist.vivo.multiwindow_dragdrop", true);
        IS_VIVO_HIDE_SPLIT_APPLIST = SystemProperties.getBoolean("persist.vivo.multiwindow_hide_applist", true);
        IS_VIVO_SPLIT_PROTECT_APP = SystemProperties.getBoolean("persist.vivo.multiwindow_split_protect_app", true);
        IS_VIVO_SPLIT_DIVIDER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_divider_special", false);
        IS_VIVO_SPLIT_DIVIDER_LAYER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_divider_layer", true);
        IS_TEMP_HIDE_STATUS_FOR_SPECIAL = SystemProperties.getBoolean("persist.vivo.multiwindow_temp_hidestatusbar_special", true);
        IS_VIVO_SPLIT_THIRD_LAUNCHER = SystemProperties.getBoolean("persist.vivo.multiwindow_split_third_launcher", true);
        IS_VIVO_INTO_SPLIT_OPTIMIZE = SystemProperties.getBoolean("persist.vivo.multiwindow_into_split_optimize", true);
        IS_VIVO_NORESIZE_INROTATE = SystemProperties.getBoolean("persist.vivo.multiwindow_noresize_inrotate", true);
        IS_VIVO_SPLIT_DOUBLE_DISPLAYS = SystemProperties.getBoolean("persist.vivo.multiwindow_split_double_displays", true);
        IS_VIVO_MODIFY_TENCENT_TOP = SystemProperties.getBoolean("persist.vivo.multiwindow_modify_tencent_top", true);
        IS_VIVO_ENTER_SPLIT_OPTIMIZE = SystemProperties.getBoolean("persist.vivo.multiwindow_enter_split_optimize", true);
        IS_VIVO_ENABLE_DELAY_HIDE_SPLITNABAR_INSPLIT = SystemProperties.getBoolean("persist.vivo.enable_delay_hide_splitnabar_insplit", true);
        IS_VIVO_FORCE_DEBUG_TASK_BOUNDS = SystemProperties.getBoolean("persist.vivo.force.debug.task.bounds", false);
        IS_VIVO_MODIFY_HOME_LAYER = SystemProperties.getBoolean("persist.vivo.multiwindow_modify_home_layer", false);
        IS_VIVO_USE_SAME_TRANSATION = SystemProperties.getBoolean("persist.vivo.multiwindow_use_same_transtion", true);
    }
}